repos:
- repo: local
  hooks:
    - id: missfisher-updater
      name: Update Versions
      entry: python xml_version_handler.py
      language: system
      files: \.xml$
      pass_filenames: true
      stages: [pre-commit]
      verbose: true
      always_run: true 