name: Upload to COS

on: [push]

jobs:
  UploadCOS:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2.3.5
    - name: Install coscmd
      run: sudo pip install coscmd
    - name: Configure coscmd
      env:
        SECRET_ID: ${{ secrets.TENCENT_SECRET_ID }}
        SECRET_KEY: ${{ secrets.TENCENT_SECRET_KEY }}
        BUCKET: missfisher-1331276814
        REGION: ap-guangzhou
      run: coscmd config -a $SECRET_ID -s $SECRET_KEY -b $BUCKET -r $REGION
    - name: Upload
      run: coscmd upload -rfs --delete ./ / --ignore "./.git/*"
